### ISSUE TITLE
Confused by path relevance computation

### ISSUE THREAD

**Issue by skydiving94** [JosuaStadelmaier/CPM#1]
Could you please explain where I can find the corresponding code for equation 4 in the paper? I am also a bit confused about the difference among a_r, r_p, and r.

**Comment by JosuaStadelmaier** [comment]
I am sorry for my very late answer.
In case you are still interested, the code for Equation 4 can be found in the function [path_relevance()](https://github.com/JosuaStadelmaier/CPM/blob/949361ac061853dc07b7363c4820083071c67995/cpm.py#L286).
More precisely, the main computations take place [here](https://github.com/JosuaStadelmaier/CPM/blob/949361ac061853dc07b7363c4820083071c67995/cpm.py#L297) and [here](https://github.com/JosuaStadelmaier/CPM/blob/949361ac061853dc07b7363c4820083071c67995/cpm.py#L334-L336)

Here is more info on **a_r**, **r_p** and **r**:
- **r** is the vector representation of the relation over which we want to make predictions.
In the code, I have named it `r_embedding`.

- **r_p** is the vector representation of a path p. (This path has been selected according to the criteria given in section 3.4 in the paper. These criteria already aim to select paths that are potentially relevant for the relation r.)
**r_p** is called `p_embedding` in the code.

- For each relation we learn a vector **a_r**, which, when taken the dot product with **r_p**, is expected to give us an estimate on how relevant the path p actually is for assessing the correctness of a „fact“ about the relation r.
In the code, I refer to **a_r** as `c_embedding`, which is probably somewhat confusing

If you have any further questions, just let me know. :)
